version: '3'
services:
  app:
    image: tomcat:9.0.30
    container_name: app
    ports:
      - "80:8080"
    restart: always
    volumes:
      - ./pis_webapp/target/demo-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    command: catalina.sh run
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: app_data
    expose:
      - "5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
