/* ADMIN */
export const SET_ADMIN_MENU_ACTIVE = 'SET_ADMIN_MENU_ACTIVE';

export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const UPDATE_USER = 'UPDATE_USER';

export const LOAD_PRODUCT_LIST = 'LOAD_PRODUCT_LIST';
export const REMOVE_PRODUCT_FROM_LIST = 'REMOVE_PRODUCT_FROM_LIST';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';

/* FRONTEND */
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const SET_ACTIVE_PRODUCT_IMAGE = 'SET_ACTIVE_PRODUCT_IMAGE';